Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

# Question 1

Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables

In [1]:
'''
Yes, 
there is a difference in the data type between the list_ and array_list variables. 
The list_ variable is a Python list, and the array_list variable is a NumPy array.
'''


'\nYes, \nthere is a difference in the data type between the list_ and array_list variables. \nThe list_ variable is a Python list, and the array_list variable is a NumPy array.\n'

# Question 2

Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing data types of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Printing data types of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Question 3

Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [7]:
'''
Yes, there will be a difference in the data type of the elements present in the array_list variable after the modification. 
The dtype=int parameter in np.array will force the elements to be converted to integers.
'''

# Printing the datatypes of the element present in the both variables

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in modified array_list
print("\nData types of elements in modified array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in modified array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Question 4

Consider the below code to answer further questions:

    
import numpy as np


num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]


num_array = np.array(object = num_list)

Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Finding the shape of num_array
shape_of_num_array = num_array.shape

# (ii) Finding the size of num_array
size_of_num_array = num_array.size

# Printing the results
print("Shape of num_array:", shape_of_num_array)
print("Size of num_array:", size_of_num_array)


Shape of num_array: (2, 3)
Size of num_array: 6


# Question 5

Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [9]:
# Creating a 3x3 matrix containing zeros
zero_matrix = np.zeros((3, 3))

# Print the resulting array
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Question 6

Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

# Printing the resulting array
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
